name: Test Day Workflow

on:
  workflow_call:
    inputs:
      day_name:
        required: true
        type: string
        description: "Name of the day directory (e.g., day_1, day_2)"

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python

      - name: Run tests for ${{ inputs.day_name }}
        uses: ./.github/actions/pytest
        with:
          day_name: ${{ inputs.day_name }}
