name: Run Tests for day_11

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - 'learnPython/day_11/**'

jobs:
  test:
    uses: ./.github/workflows/reusable-test-day.yml
    with:
      day_name: day_11
